server:
  port: 8083

spring:
  application:
    name: Security
  main:
    debug:
      enabled:true
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: ASDFG123zx#
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init-mode: true

hibernate:
  id:
    new_generator_mappings: false

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
