server:
  port: 8082
eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: BACKENDDB
          uri: lb://BACKENDDB
          predicates:
            - Path=/info/** , /tweet/** , /payment/**
          filters:
            - AuthFilter

        - id: SECURITY
          uri: lb://SECURITY
          predicates:
            - Path=/identity/** , /register/**

